# Generated by Django 4.1.3 on 2023-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, verbose_name='수령인')),
                ('item_phone', models.CharField(default='', max_length=128, verbose_name='수령인 전화번호')),
                ('item_address', models.TextField(verbose_name='수령인 주소')),
                ('item_require', models.CharField(max_length=128, verbose_name='요구사항')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'item',
            },
        ),
    ]
