# Generated by Django 4.2.4 on 2023-08-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('setPrice', models.IntegerField()),
                ('type', models.CharField(choices=[('Burger', 'Burger'), ('Drink', 'Drink'), ('Dessert', 'Dessert')], max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='burger')),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
