# Generated by Django 4.2.4 on 2023-08-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_alter_burger_setprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='setPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
